import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Providers } from "@/utils/provider";
const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "@/components/AuthProvider";
// import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="whole">
          <div className="main_container">
            <Providers>
              <AuthProvider>
                <NavBar></NavBar>
                {children}
                <Footer></Footer>
              </AuthProvider>
            </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
